### ISSUE TITLE
multiple canvas support for Bivot

### ISSUE THREAD

**Issue by yellowtailfan** [bandicoot-imaging-sciences/bivot#11]
I found a multi-canvas example in Three.js. Looks like we just need to call Bivot like this:
```
bivot_kimono = new Bivot(<kimono options>);
bivot_wallet = new Bivot(<wallet options>);
```
I think using new means the local scope is bound to the created object. Otherwise it seems to be shared across each call.

We don't need to add lots of `this` prefixes inside Bivot, it's only required if we want methods or attributes to be visible from outside Bivot.

https://threejs.org/examples/?q=canvas#webgl_multiple_canvases_circle

**Comment by volrak** [comment]
Multiple different Bivot instances can currently be placed on the same page, by passing different canvasID and overlayID values into the constructor.
