### ISSUE TITLE
lighting goes diagonal in portrait mode

### ISSUE THREAD

**Issue by yellowtailfan** [bandicoot-imaging-sciences/bivot#17]
When the object is rotated to portrait orientation and viewed with area lighting, the lighting appears to travel diagonally across the material.

**Comment by petrochemical** [comment]
Is this something to do with a half angle being halved so a 90 degree rotation turns into a 45 degree rotation?

**Comment by yellowtailfan** [comment]
As @volrak suggested, the object orientation had been left out of the normalMatrix calculation. So the normals were only correct when the object was not moved or rotated.

I've switched the normalMatrix calculation to use the ThreeJS defaults, and verified it works using several textures with both BIS (0) and MR (1) BRDF models.
