### ISSUE TITLE
listen() method on GUI controls blocks text input

### ISSUE THREAD

**Issue by yellowtailfan** [bandicoot-imaging-sciences/bivot#19]
We can leave out listen(), but this means when the values change (e.g. when changing the scan, which brings in a new state), the displayed values are wrong.

A work around might be to manually loop over the controls after the state changes, as shown in this answer:
https://stackoverflow.com/a/24602975

**Comment by yellowtailfan** [comment]
Displayed values are now updating when the state changes when switching scans (a1508a1becd740e7ef48381f2603266d3016369c). However, controls with listen() still can't be changed by typing into the text boxes.

**Comment by volrak** [comment]
This issue no longer occurs since the legacy dat.gui interface is no longer in use for text field entry.
