### ISSUE TITLE
Background colour should be post-gamma

### ISSUE THREAD

**Issue by yellowtailfan** [bandicoot-imaging-sciences/bivot#23]
Currently `state.background` is applied in linear colour space, which means the actual displayed background colour has a gamma applied on top of the value in `state.background`.

I think it would be more intuitive if the background colour was specified in the displayed colour space (i.e. in sRGB). This would also make it easier to match the background colour with the colour of other HTML page elements outside the Bivot canvas.

**Comment by yellowtailfan** [comment]
It looks like Three.js has a method to help with this called [Color.convertSRGBToLinear](https://threejs.org/docs/#api/en/math/Color).

**Comment by volrak** [comment]
This was fixed in 17dfcba5.
